### PR TITLE
Arms: WPN REL CCRP Automatic Release

### PR DESCRIPTION
**Pull request by BobDotCom**
## Description
This PR implements automatic release of A/G weapons in CCRP mode. Weapons can now be dropped as they would be IRL. Pickle button (WPN REL) is pressed and held a few seconds prior to the calculated bombing solution, and the computer will automatically release the bombs when ready.

## Demonstration
You can see when the trigger is pressed/released in the nasal console.

https://youtu.be/JX2pNDZjxMs

## TODO List

- [x] Make sure listener is always cleaned up in edge cases.
- [x] HUD FPM should flash upon release while WPN REL is held
    Screenshot 2023-08-25 at 4 42 28 PM
- Solution parameter improvements (Non-essential, can be completed after merging)
  - [ ] Should be variable based on altitude
  - [ ] Maybe use time to drop instead of distance as it accounts for speed
- Allow for theoretical implementation on other aircraft
  - [x] Remove dependency on HUD code for distance calculations
    - Note: This would also allow for payload to be dropped if HUD is inop
  - [x] Change property to `payload/armament/distCCRP` instead of `f16/hud/distCCRP`

### CODE REVIEW

**Comment by BobDotCom** [comment]
Known bug: this prevents launching a/a weapons right now

**Comment by SammySkycrafts** [comment]
> Known bug: this prevents launching a/a weapons right now

Implementing #448 may result in a somewhat simple fix for this, though implementing it could be more work than figuring a fix with the current system.

```if masterMode = A/G and releaseMode = CCRP:
           run ccrpAutoRel
     else
          don't run ccrpAutoRel```

**Comment by BobDotCom** [comment]
Two things to note:
1. I applied the release system to unguided weapons too. If that's incorrect, it can be removed from the list I added in 42c7ca2e42ac994c505463283bc4c4dd58f5cdfd.
2. Currently, it depends on code executed in the HUD. It shouldn't, but I haven't ported that code over to be used in the other spot yet. Should probably be changed before merging.


Otherwise, it should work now.

**Comment by BobDotCom** [comment]
Needs testing, but otherwise ready to merge.

**Comment by NikolaiVChr** [comment]
There is already code to blink the FPM for CCIP, I think it would be better if you modify that instead of adding new code inside the code. Why did you do it inside, you don't want the bank angle indicator to blink also, or?

**Comment by NikolaiVChr** [comment]
Is this tested with dropping pairs and/or rippling?

**Comment by NikolaiVChr** [comment]
Instead of checking all bomb types in firecontrol, its better to test if the weapon is in dualWeapons. dualWeapons is those that should be droppable with ccrp anyway.

Not sure why the agm154 is in that list though..

**Comment by SammySkycrafts** [comment]
> Not sure why the agm154 is in that list though..

Maybe we do that because we do not have side-by-side / tandem impact modelled, so we just allow dual release instead

**Comment by NikolaiVChr** [comment]
I did not think my commit, would trigger conflicts, sorry. I did it to prepare for this PR.

**Comment by NikolaiVChr** [comment]
Also the line `print("tgt not found");`
Could be changed to `printDebug("CCRP: tgt not found");`

**Comment by SammySkycrafts** [comment]
> Is this tested with dropping pairs and/or rippling?

Ripple tested and working, @BobDotCom mentioned a pair release the other day so presumably that works too.

**Comment by BobDotCom** [comment]
> There is already code to blink the FPM for CCIP, I think it would be better if you modify that instead of adding new code inside the code. Why did you do it inside, you don't want the bank angle indicator to blink also, or?

Moved the logic to that check.

> Is this tested with dropping pairs and/or rippling?

Yes

> Instead of checking all bomb types in firecontrol, its better to test if the weapon is in the CCIP_CCRP vector.
That vector is a new addition I just committed.

Done

> Also the line `print("tgt not found");` Could be changed to `printDebug("CCRP: tgt not found");`

That line should pretty much never be called, only when the missile loses lock mid-function. I updated it though.

**Comment by BobDotCom** [comment]
Ready to merge

**Pull request merged**
