### PR TITLE
Add Tacview Support

### PR DESCRIPTION
**Pull request by Marsdolphin**
Added Tacview Support for the F-16

### CODE REVIEW

**Comment by NikolaiVChr** [comment]
Thanks

Looks like you ported over half of mig21 radar though, at least stuff we don't need.
And you labeled the aircraft as mig-29.

**Comment by Marsdolphin** [comment]
Really xD

**Comment by Marsdolphin** [comment]
I took the nasal from the mig-21

**Comment by NikolaiVChr** [comment]
> Name=MiG-29_9-12

**Comment by Marsdolphin** [comment]
oof Lemme change it

**Comment by Marsdolphin** [comment]
Done

**Comment by NikolaiVChr** [comment]
nice.

also remove the radar stuff please, no reason to have 1.5 radars, will only degrade performance..

**Comment by Marsdolphin** [comment]
Ok no more 1.5 radars

**Comment by NikolaiVChr** [comment]
Does it work?

**Comment by Marsdolphin** [comment]
Not sure not tested yet

**Comment by l0k1** [comment]
Just removing that file wont work. Youll have to edit tacview.nas as well. 

As an aside, this was not meant to be copy/pasted to other planes.

**Comment by l0k1** [comment]
Should also add that this wont include viewing missiles.

**Comment by Marsdolphin** [comment]
Hmm, still needs more work

**Comment by NikolaiVChr** [comment]
Now included: 2ab66ec721d1b8dbdd2cf1bb995cc071ea13664b

**Pull request closed without merging**
