### PR TITLE
AP: Fix HDG SEL behavior and improve a few behaviors

### PR DESCRIPTION
**Pull request by Octal450**
Fixes issue #384 

A/P HDG SEL mode now follows the cockpit indicator, and fixed a few misc issues with the implementation, redesigned the control loop slightly to make it smooth

Kind Regards,
Josh

### CODE REVIEW

**Comment by NikolaiVChr** [comment]
Why rename the captain heading property?

**Comment by Octal450** [comment]
@NikolaiVChr because the original property was wrong. It supposed to be heading-indicator/heading-bug-deg. Its not the offset property and there is no 'heading-indicator-fg' used in the f16. It was a left-over property from something old probably.

Kind Regards,
Josh

**Comment by NikolaiVChr** [comment]
`instrumentation/heading-indicator-fg/offset-deg`
Is used by internally by FG, I did not choose that property by random.

**Comment by Octal450** [comment]
How can that be,
After my rename, the property does not even exist anymore. 

image


Kind Regards,
Josh

**Comment by NikolaiVChr** [comment]
No, but when it exist it is used by C++ in FG
See:
src\Instrumentation\heading_indicator_fg.cxx

**Comment by Octal450** [comment]
@NikolaiVChr Interesting. Probably best to mirror the property there. I'll make the change and commit it.

Kind Regards,
Josh

**Comment by Octal450** [comment]
@NikolaiVChr I've just glanced through the code of that C++, and it seems that this is the magnetic OFFSET value... not the heading bug. Why are you putting heading bug there? I don't understand. You should put the offset property there instead - and even then, it doesn't look like you're using the heading-indicator-fg instrument anywhere. Please explain.

Kind Regards,
Josh

**Comment by NikolaiVChr** [comment]
I don't really remember why I named it as such. Or if the C++ has changed since I made it.
I will trust you and merge it as it is. And hope nothing get broken.

**Comment by Octal450** [comment]
Thanks! :)

Kind Regards,
Josh

**Pull request merged**
