### PR TITLE
Anim: EPU Air lamp now animated, besides Hydrazn

### PR DESCRIPTION
**Pull request by ph-jake**

### CODE REVIEW

**Comment by NikolaiVChr** [comment]
Sorry, but the logic of the hydrazine was already as described in the manual, not sure why you changed it.

And EPU AIR has to do with mainatance crew operations, without attached equipment it will never come on.

**Comment by ph-jake** [comment]
> Sorry, but the logic of the hydrazine was already as described in the manual, not sure why you changed it.

The logic output of the block was indeed working as expected. The logic expression though was based on a derived value (epu-require-hydrazine) of the 'real property' to control the "light"_epu_*" light: "epu-cmd". In order to create symmetry with the logic for the "light_epu_air" object I've added this property here as well. The logic output of the block does not change from this.

> And EPU AIR has to do with mainatance crew operations, without attached equipment it will never come on.

So what is powering the EPU when N2 > 75% then? The "epu-require-hydrazine" property goes off, as does the "light"_epu_hydrazine" light.

Indeed if this is limited to maintenance, a "epu-require-bleed-air" would need to be created. 

I'll keep reading into this.

**Comment by NikolaiVChr** [comment]
It was on purpose it only depended on the 'derived' property, that property is designed to control that light.

As you can see the 'derived property is created using:

```xml
<switch name="elec/sources/epu-require-hydrazine">
			<default value="0"/>
			<test logic="AND" value="1">
				elec/sources/epu-cmd == 1
				/engines/engine/n2 lt 75
			</test>
		</switch>```


> So what is powering the EPU when N2 > 75% then?

The engine RPM is.

**Comment by NikolaiVChr** [comment]
I did some digging, seems I remember wrong, on the AIR light you were almost right. It stay on even if it wants to use hydrazine.

image


So just remove:

```xml
<not>
          <property>fdm/jsbsim/elec/sources/epu-require-hydrazine</property>
        </not>
```

But for HYDRAZIN light, there is no reason to add the check for `elec/sources/epu-cmd` as that is done already somewhere else.

**Comment by ph-jake** [comment]
Okay, that sounds even better, so the bleed air seems to be the main power source for the EPU, with hydrazine in support, if needed.

I'll push a new change with this, including the change you want on the hydrazine light, I'm fine with that too.

**Pull request merged**
