### PR TITLE
Nasal updates (working towards common modules). Improvements to panels

### PR DESCRIPTION
**Pull request by Zaretto**
- Update radar to latest version; merge with pre-existing f16 changes. This also changes the wcs-mode into an int, but most of the rest of the interfaces are identical.

- added latest version of frame notification (that supports dynamically adding to the list of monitored properties)
- revised exec to use the revised frame notification

NOTE: The f16.nas contains a subsystem that requests the frame notifier to provide all of the properties that were previously in exec.nas. This code is not the recommended way to do things as now all exec frame notifier based modules should request the properties that are needed in the frame notification during intialization (or construction).

3D model changes:
* IPC - remodel 3d; better quality texture, ALS backlighting and support for block differences
* AUX PANEL (left front) remodeled with 3d switches, support for pre and post block 15 autopilot, connected to properties and added ALS backlighting.
* Lighting panel (right console) - added lighting knobs that connect to the appropriate properties.
* Added new effects to support backlighting and ALS cockpit shadow. NOTE: ALS cockpit shadow will not currently work that well as the panels need to be in the correct absolute position.

### CODE REVIEW

**Comment by NikolaiVChr** [comment]
I have made a new branch (newRadar) where I have merged these updates with Jmav16's changes. Hope the merge went well. Thanks for the updates Richard, sorry for taking so long to check it.

Some feedback:

For testing the RWR, the first thing I did was press 'r' to silence the radar to test if rwr still worked even when radar was silent. However I was unable to make the radar go silent. (bug)

The Rwr does not pick up SAMs or MPs. And they are designated on HUD as 'AI', hmm they probably do show up but since they are set as AI they dont look right on rwr and will not move into the inner circle, when they are a threat. (bug)

When I switch on masterarm, until I selected first target, the callsign window in HUD showed 'window3' I think. (bug)

The masterarm panel looks good, although dark and unable to read it when there is not direct sunlight on it. (ALS)

'E' seems to cycle radar distance. It was on purpose I had set it to not cycle, so could just quickly click it some times, to get max if needed. You disagree that a good idea?

When I click the up arrow to increase radar distance on the mfd, it also cycles instead of stop at max.

The radar distance that can be toggled is changed, its now (5,10,20,40,50,100,200). This probably also affects the coupled mode (CPL) of the HSD, so it dont choose the right distance to show. (bug)
Note to this: If you want the radar to be same as F15, maybe pass it a vector of allowed distances, so we can have different ones in f16 from f15.

With 'y' I can select targets outside radar cone. (bug)

When selected something and it moves out of radarcone, it still shows its altitude and distance on radar, instead of XX.X etc (bug)

The little line from the bore-aim-cross that points to selection is there even when target out of radarcone. (bug)

When I on the radar MFD click A4 to limit the radar width or B8 to limit the numbers of bars, the echoes still show when they shouldn't. (bug)

**Comment by NikolaiVChr** [comment]
But damn, thats alot of changes you did. Hope we get the issues resolved, merge this in, and then get it on fgaddon.

@JMaverick16 if you read this, please dont commit anything till branch newRadar has been merged in. Else we have to sit and sort out the merge conflicts again.

**Comment by it0uchpods** [comment]
@NikolaiVChr did you happen to test the autopilot switches in the panel?
J

**Comment by NikolaiVChr** [comment]
No, but you can just pull branch newRadar and test it. You are probably best suited to test it anyway.

**Comment by it0uchpods** [comment]
OK, Will do.
J

**Comment by it0uchpods** [comment]
OK @NikolaiVChr @Zaretto 
In the block 10/15 version, the Roll and Pitch switches are mapped to the backwards properties, roll is controlling pitch switch, and pitch is controlling roll switch, need to flip the properties.

Also, can you make the drag for the switches vertical? It makes no sense to drag horizontal when the switches move vertical.

Kind Regards,
Josh

**Comment by NikolaiVChr** [comment]
Good that you noted those things, unless you do a pull request to fix it on newRadar branch, or Richard fix it, I think its small things that can easy be fixed after the big merge into master.

**Comment by it0uchpods** [comment]
I was planning to correct it tomorrow, if no-one else had, it's too late here now :D

J

**Comment by Zaretto** [comment]
Almost certainly most of the radar problems are probably regressions from the new radar code that I merged as I didn't pickup on these specifics when I did the merge (which wasn't exactly straightforwards). Hopefully we can standardise the radar simulation so this will be the last time we get hit with this sort of problem.

> 'E' seems to cycle radar distance...you disagree that a good idea?

No objection to the "nowrap" approach. It's just something that got lost in the merge when I added the specification of the radar ranges. A simple property flag to control this (that can be set into a property in the -set.xml) is the way we should do this.

> If you want the radar to be same as F15, maybe pass it a vector of allowed distances, so we can have different ones in f16 from f15.
Probably that's what I intended; again it should be set in the -set

----------------
Let me know if I need to do anything to help fix these; otherwise I'm going to assume that you know what to do.

All I suggest is that we keep all aircraft specific code out of these modules; again I'm happy to help with this.
------------------

Once this merge is done there is more work I'd like to do to improve the 3d and other things; but I decided to stop until we merged this to avoid making the pull request too big

**Comment by NikolaiVChr** [comment]
More 3D sounds great. :)
The reason I didnt just fix all these radar things is that we probably would want any change to the radar to be feed back into f15 and opposite.
Okay, will look into fixing them, and will try to fix in a way that dont break the radar in f15. Will probably have to ask you lots of questions, but can do that on discord.

Will take me some time, since I am not doing FG fulltime atm. so be patient guys. :)

**Pull request merged**
